### ISSUE TITLE
效率是问题，如果UI足够复杂

### ISSUE THREAD

**Issue by kane9527-e** [zzjfengqing/ET-EUI#3]
很多人好怕效率问题

**Comment by zzjfengqing** [comment]
如果有效率问题，那就贴出性能数据吧，如果只是主观臆断的话，那您觉得是对的就是对的吧。客观事实是这做法这个在多款高流水的mmorpg游戏里都验证过，每款游戏呢，也有上百多个复杂界面，从性能监控平台的数据和玩家实际游玩体验，都没反应过这个所谓的效率问题。
